

#BSUB -P run_yli11_
#BSUB -o run_yli11_2023-01-10/log_files/REDI_%J_%I.out -e run_yli11_2023-01-10/log_files/REDI_%J_%I.err
#BSUB -n 20
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "REDI[1-24]"



module purge

id=$LSB_JOBINDEX
COL1=`head -n $id bam.list|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id bam.list|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id bam.list|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id bam.list|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id bam.list|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id bam.list|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id bam.list|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id bam.list|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id bam.list|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id bam.list|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

ncore=20
mem=4000
module load python/2.7.13
python ~/HemTools/share/script/REDItoolDnaRna.py -t 20 -i ${COL1} -d -D -f /home/yli11/Data/Human/hg19/fasta/Homo_sapiens.add_chr.GRCh37.dna.primary_assembly.fa -G ~/Data/Human/hg19/annotations/gencode.v30lift37.annotation.st.gtf.gz -o ${COL1}_REDItool_results

