

#BSUB -P run2_yli11
#BSUB -o run2_yli11_2023-01-12/log_files/AI_%J_%I.out -e run2_yli11_2023-01-12/log_files/AI_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=30000]"
#BSUB -J "AI[1-24]"



module purge

id=$LSB_JOBINDEX
COL1=`head -n $id AI.list|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id AI.list|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id AI.list|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id AI.list|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id AI.list|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id AI.list|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id AI.list|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id AI.list|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id AI.list|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id AI.list|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

mem=30000
module load python/2.7.13
python ~/HemTools/share/script/tabulate_reads_AtoI-stranded.py ${COL1}

