

#BSUB -P cut_run
#BSUB -o cut_run_rfeng_2022-10-06.BWA.message_%J_%I.out -e cut_run_rfeng_2022-10-06.BWA.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=6000]"
#BSUB -J "BWA[1-9]"
module purge
module load bwa/0.7.16a
module load samtools/1.7

id=$LSB_JOBINDEX
COL1=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id cut_run_rfeng_2022-10-06.bwa.input|tail -n1`

bwa mem -t 6 /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/bwa_16a_index/hg19.fa ${COL1} ${COL2} |samtools view -@ 6 -bS - > ${COL3}.bam

		