

#BSUB -P cut_run
#BSUB -o cut_run_rfeng_2022-10-06.macs2.message_%J_%I.out -e cut_run_rfeng_2022-10-06.macs2.message_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=80000]"
#BSUB -J "macs2[1-8]"
module purge
#BSUB -w "ended(170665602)"
module load samtools/1.10
module load bedtools/2.29.2
module load conda3
source activate /home/yli11/.conda/envs/py2
module load gcc/6.3.0
export PATH=$PATH:"/home/yli11/HemTools/bin"
module load R/3.5.1

id=$LSB_JOBINDEX
COL1=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id peakcall.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id peakcall.tsv|tail -n1`

module load conda3
source activate /home/yli11/.conda/envs/r_env
samtools view -b ${COL1}.markdup.bam chr1 > ${COL1}.chr1.ef57cd916021.bam;samtools index ${COL1}.chr1.ef57cd916021.bam
run_ATACseqQC.R ${COL1}.chr1.ef57cd916021.bam hg19
rm ${COL1}.chr1.ef57cd916021.bam*
module load macs2/2.1.1
macs2 callpeak -t ${COL1}.bam -c ${COL2}.bam -f BAMPE -B --keep-dup all -n ${COL3}
macs2 bdgcmp -t ${COL3}_treat_pileup.bdg -c ${COL3}_control_lambda.bdg -m qpois -o ${COL3}_treat_pvalue.bdg
macs2 bdgcmp -t ${COL3}_treat_pileup.bdg -c ${COL3}_control_lambda.bdg -m FE -o ${COL3}_FE.bdg
macs2 bdgcmp -t ${COL3}_treat_pileup.bdg -c ${COL3}_control_lambda.bdg -m logLR -o ${COL3}_logLR.bdg -p 0.01
macs2 bdgpeakcall -i ${COL3}_treat_pvalue.bdg -c 1.301 -l 100 -g 75 -o ${COL3}_bdgpeaks.bed
bedtools intersect -a ${COL3}_peaks.narrowPeak -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}_peaks.rmblck.narrowPeak
bedtools intersect -a ${COL3}_bdgpeaks.bed -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}_bdgpeaks.rmblck.bed
annot_gene_features.py -f ${COL3}_peaks.rmblck.narrowPeak -o ${COL3}_peaks.rmblck.narrowPeak.annot.tsv -g hg19
pie_plot.py -f ${COL3}_peaks.rmblck.narrowPeak.annot.tsv --order Exon,Promoter,5UTR,3UTR,Intron,Intergenic --use_col -1 --header -o ${COL3}_peaks.rmblck.narrowPeak.genomic_features.pie_chart
module load python/2.7.13;/home/yli11/HemTools/bin/calculate_FRiP.py ${COL1}.bam ${COL3}_peaks.rmblck.narrowPeak CHIP
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}_treat_pvalue.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}_treat_pvalue.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}_FE.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}_FE.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}_logLR.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}_logLR.bw
module load conda3
source activate /home/yli11/.conda/envs/r_env
samtools view -b ${COL1}.rmdup.uq.rmchrM.markdup.bam chr1 > ${COL1}.rmdup.uq.rmchrM.chr1.ef57cd916021.bam;samtools index ${COL1}.rmdup.uq.rmchrM.chr1.ef57cd916021.bam
run_ATACseqQC.R ${COL1}.rmdup.uq.rmchrM.chr1.ef57cd916021.bam hg19
rm ${COL1}.rmdup.uq.rmchrM.chr1.ef57cd916021.bam*
module load macs2/2.1.1
macs2 callpeak -t ${COL1}.rmdup.uq.rmchrM.bam -c ${COL2}.rmdup.uq.rmchrM.bam -f BAMPE -B --keep-dup all -n ${COL3}.rmdup.uq.rmchrM
macs2 bdgcmp -t ${COL3}.rmdup.uq.rmchrM_treat_pileup.bdg -c ${COL3}.rmdup.uq.rmchrM_control_lambda.bdg -m qpois -o ${COL3}.rmdup.uq.rmchrM_treat_pvalue.bdg
macs2 bdgcmp -t ${COL3}.rmdup.uq.rmchrM_treat_pileup.bdg -c ${COL3}.rmdup.uq.rmchrM_control_lambda.bdg -m FE -o ${COL3}.rmdup.uq.rmchrM_FE.bdg
macs2 bdgcmp -t ${COL3}.rmdup.uq.rmchrM_treat_pileup.bdg -c ${COL3}.rmdup.uq.rmchrM_control_lambda.bdg -m logLR -o ${COL3}.rmdup.uq.rmchrM_logLR.bdg -p 0.01
macs2 bdgpeakcall -i ${COL3}.rmdup.uq.rmchrM_treat_pvalue.bdg -c 1.301 -l 100 -g 75 -o ${COL3}.rmdup.uq.rmchrM_bdgpeaks.bed
bedtools intersect -a ${COL3}.rmdup.uq.rmchrM_peaks.narrowPeak -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak
bedtools intersect -a ${COL3}.rmdup.uq.rmchrM_bdgpeaks.bed -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.rmdup.uq.rmchrM_bdgpeaks.rmblck.bed
annot_gene_features.py -f ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak -o ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak.annot.tsv -g hg19
pie_plot.py -f ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak.annot.tsv --order Exon,Promoter,5UTR,3UTR,Intron,Intergenic --use_col -1 --header -o ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak.genomic_features.pie_chart
module load python/2.7.13;/home/yli11/HemTools/bin/calculate_FRiP.py ${COL1}.rmdup.uq.rmchrM.bam ${COL3}.rmdup.uq.rmchrM_peaks.rmblck.narrowPeak CHIP
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup.uq.rmchrM_treat_pvalue.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup.uq.rmchrM_treat_pvalue.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup.uq.rmchrM_FE.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup.uq.rmchrM_FE.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup.uq.rmchrM_logLR.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup.uq.rmchrM_logLR.bw
module load conda3
source activate /home/yli11/.conda/envs/r_env
samtools view -b ${COL1}.rmdup.markdup.bam chr1 > ${COL1}.rmdup.chr1.ef57cd916021.bam;samtools index ${COL1}.rmdup.chr1.ef57cd916021.bam
run_ATACseqQC.R ${COL1}.rmdup.chr1.ef57cd916021.bam hg19
rm ${COL1}.rmdup.chr1.ef57cd916021.bam*
module load macs2/2.1.1
macs2 callpeak -t ${COL1}.rmdup.bam -c ${COL2}.rmdup.bam -f BAMPE -B --keep-dup all -n ${COL3}.rmdup
macs2 bdgcmp -t ${COL3}.rmdup_treat_pileup.bdg -c ${COL3}.rmdup_control_lambda.bdg -m qpois -o ${COL3}.rmdup_treat_pvalue.bdg
macs2 bdgcmp -t ${COL3}.rmdup_treat_pileup.bdg -c ${COL3}.rmdup_control_lambda.bdg -m FE -o ${COL3}.rmdup_FE.bdg
macs2 bdgcmp -t ${COL3}.rmdup_treat_pileup.bdg -c ${COL3}.rmdup_control_lambda.bdg -m logLR -o ${COL3}.rmdup_logLR.bdg -p 0.01
macs2 bdgpeakcall -i ${COL3}.rmdup_treat_pvalue.bdg -c 1.301 -l 100 -g 75 -o ${COL3}.rmdup_bdgpeaks.bed
bedtools intersect -a ${COL3}.rmdup_peaks.narrowPeak -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.rmdup_peaks.rmblck.narrowPeak
bedtools intersect -a ${COL3}.rmdup_bdgpeaks.bed -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.rmdup_bdgpeaks.rmblck.bed
annot_gene_features.py -f ${COL3}.rmdup_peaks.rmblck.narrowPeak -o ${COL3}.rmdup_peaks.rmblck.narrowPeak.annot.tsv -g hg19
pie_plot.py -f ${COL3}.rmdup_peaks.rmblck.narrowPeak.annot.tsv --order Exon,Promoter,5UTR,3UTR,Intron,Intergenic --use_col -1 --header -o ${COL3}.rmdup_peaks.rmblck.narrowPeak.genomic_features.pie_chart
module load python/2.7.13;/home/yli11/HemTools/bin/calculate_FRiP.py ${COL1}.rmdup.bam ${COL3}.rmdup_peaks.rmblck.narrowPeak CHIP
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup_treat_pvalue.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup_treat_pvalue.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup_FE.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup_FE.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.rmdup_logLR.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.rmdup_logLR.bw
module load conda3
source activate /home/yli11/.conda/envs/r_env
samtools view -b ${COL1}.markdup.uq.markdup.bam chr1 > ${COL1}.markdup.uq.chr1.ef57cd916021.bam;samtools index ${COL1}.markdup.uq.chr1.ef57cd916021.bam
run_ATACseqQC.R ${COL1}.markdup.uq.chr1.ef57cd916021.bam hg19
rm ${COL1}.markdup.uq.chr1.ef57cd916021.bam*
module load macs2/2.1.1
macs2 callpeak -t ${COL1}.markdup.uq.bam -c ${COL2}.markdup.uq.bam -f BAMPE -B --keep-dup all -n ${COL3}.markdup.uq
macs2 bdgcmp -t ${COL3}.markdup.uq_treat_pileup.bdg -c ${COL3}.markdup.uq_control_lambda.bdg -m qpois -o ${COL3}.markdup.uq_treat_pvalue.bdg
macs2 bdgcmp -t ${COL3}.markdup.uq_treat_pileup.bdg -c ${COL3}.markdup.uq_control_lambda.bdg -m FE -o ${COL3}.markdup.uq_FE.bdg
macs2 bdgcmp -t ${COL3}.markdup.uq_treat_pileup.bdg -c ${COL3}.markdup.uq_control_lambda.bdg -m logLR -o ${COL3}.markdup.uq_logLR.bdg -p 0.01
macs2 bdgpeakcall -i ${COL3}.markdup.uq_treat_pvalue.bdg -c 1.301 -l 100 -g 75 -o ${COL3}.markdup.uq_bdgpeaks.bed
bedtools intersect -a ${COL3}.markdup.uq_peaks.narrowPeak -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.markdup.uq_peaks.rmblck.narrowPeak
bedtools intersect -a ${COL3}.markdup.uq_bdgpeaks.bed -b /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.blacklist.bed -v > ${COL3}.markdup.uq_bdgpeaks.rmblck.bed
annot_gene_features.py -f ${COL3}.markdup.uq_peaks.rmblck.narrowPeak -o ${COL3}.markdup.uq_peaks.rmblck.narrowPeak.annot.tsv -g hg19
pie_plot.py -f ${COL3}.markdup.uq_peaks.rmblck.narrowPeak.annot.tsv --order Exon,Promoter,5UTR,3UTR,Intron,Intergenic --use_col -1 --header -o ${COL3}.markdup.uq_peaks.rmblck.narrowPeak.genomic_features.pie_chart
module load python/2.7.13;/home/yli11/HemTools/bin/calculate_FRiP.py ${COL1}.markdup.uq.bam ${COL3}.markdup.uq_peaks.rmblck.narrowPeak CHIP
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.markdup.uq_treat_pvalue.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.markdup.uq_treat_pvalue.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.markdup.uq_FE.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.markdup.uq_FE.bw
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/wigToBigWig ${COL3}.markdup.uq_logLR.bdg /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../hg19/hg19.chrom.sizes ${COL3}.markdup.uq_logLR.bw
SEACR_1.3.sh ${COL1}.markdup.fragments.bdg ${COL2}.markdup.fragments.bdg norm relaxed ${COL3}.SEACR.markdup
SEACR_1.3.sh ${COL1}.rmdup.fragments.bdg ${COL2}.rmdup.fragments.bdg norm relaxed ${COL3}.SEACR.rmdup
SEACR_1.3.sh ${COL1}.rmdup.uq.fragments.bdg ${COL2}.rmdup.uq.fragments.bdg norm relaxed ${COL3}.SEACR.rmdup.uq

		