

#BSUB -P rna_seq_va
#BSUB -o rna_seq_variant_call_yli11_2023-01-09/log_files/email_%J_%I.out -e rna_seq_variant_call_yli11_2023-01-09/log_files/email_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "email[1-1]"

#BSUB -w "ended(179055956) && ended(179055957) && ended(179055958) && ended(179055959) && ended(179055960)"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

module load python/2.7.13
cd rna_seq_variant_call_yli11_2023-01-09
mv *.lsf log_files
mkdir final_results
mv *final*.vcf final_results
send_email_v1.py -m "RNA-seq variant call is finished!" -j rna_seq_variant_call_yli11_2023-01-09

