

#BSUB -P rna_seq_va
#BSUB -o rna_seq_variant_call_yli11_2023-01-09/log_files/QC1_%J_%I.out -e rna_seq_variant_call_yli11_2023-01-09/log_files/QC1_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "QC1[1-24]"



module purge

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id fastq.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

module load fastqc/0.11.5
ncore=1
mem=4000
fastqc ${COL1} -o rna_seq_variant_call_yli11_2023-01-09
fastqc ${COL2} -o rna_seq_variant_call_yli11_2023-01-09

