

#BSUB -P rna_seq_va
#BSUB -o rna_seq_variant_call_yli11_2023-01-09/log_files/sam_%J_%I.out -e rna_seq_variant_call_yli11_2023-01-09/log_files/sam_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=20000]"
#BSUB -J "sam[1-24]"

#BSUB -w "ended(179055958[*])"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id fastq.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

ncore=1
mem=20000
module load samtools/1.9
module load bcftools/1.15.1
cd rna_seq_variant_call_yli11_2023-01-09
samtools mpileup --uncompressed --output-tags DP,AD -f /home/yli11/Data/Human/hg19/index/samtools_GATK_index/Homo_sapiens.add_chr.GRCh37.dna.primary_assembly.reordered.fa ${COL3}Aligned.sortedByCoord.out.bam | bcftools call --consensus-caller > ${COL3}.samtools.vcf
vcfutils.pl varFilter -d 10 -p ${COL3}.samtools.vcf > ${COL3}.samtools.filter.vcf
bcftools +fill-tags ${COL3}.samtools.filter.vcf  -- -t AF > ${COL3}.samtools.final.vcf

