

#BSUB -P rna_seq_va
#BSUB -o rna_seq_variant_call_yli11_2023-01-09/log_files/STAR_%J_%I.out -e rna_seq_variant_call_yli11_2023-01-09/log_files/STAR_%J_%I.err
#BSUB -n 4
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=20000]"
#BSUB -J "STAR[1-24]"

#BSUB -w "ended(179055956[*])"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id fastq.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

module load star/2.5.3a
ncore=4
mem=20000
cd rna_seq_variant_call_yli11_2023-01-09
STAR --twopassMode Basic --genomeDir /research/dept/hem/common/sequencing/chenggrp/pipelines/hg19/hg19_star_253a_index/ --readFilesIn ${COL3}_val_1.fq ${COL3}_val_2.fq --runThreadN $ncore --outFileNamePrefix ${COL3} --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMattributes Standard --sjdbScore 1

