

#BSUB -P rna_seq_va
#BSUB -o rna_seq_variant_call_yli11_2023-01-09/log_files/vcf_%J_%I.out -e rna_seq_variant_call_yli11_2023-01-09/log_files/vcf_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=30000]"
#BSUB -J "vcf[1-24]"

#BSUB -w "ended(179055958[*])"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id fastq.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

ncore=1
mem=30000
module load picard/2.9.4 gatk/3.5 samtools/1.7
bam=${COL3}
jid=rna_seq_variant_call_yli11_2023-01-09
ref="/home/yli11/Data/Human/hg19/fasta/Homo_sapiens.add_chr.GRCh37.dna.primary_assembly.reordered.fa"
millsIndels="/datasets/public/genomes/hsapiens/hg19/SNPS/gatk_bundle/hg19_2.8/hg19/Mills_and_1000G_gold_standard.indels.hg19.vcf"
KGIndels="/datasets/public/genomes/hsapiens/hg19/SNPS/gatk_bundle/hg19_2.8/hg19/1000G_phase1.indels.hg19.vcf"
dbSNP138="/datasets/public/genomes/hsapiens/hg19/SNPS/gatk_bundle/hg19_2.8/hg19/dbsnp_138.hg19.vcf"
cd $jid
echo -e "["$(date)"]\tRunning picard.."
java -jar /hpcf/apps/picard/install/2.9.4/picard.jar AddOrReplaceReadGroups I=${bam}Aligned.sortedByCoord.out.bam O=${bam}Aligned.sortedByCoord.rg_added.bam SO=coordinate RGID=${bam} RGLB=${bam} RGPL=illumina RGPU=Hart_Center RGSM=${bam}
java -jar /hpcf/apps/picard/install/2.9.4/picard.jar MarkDuplicates I=${bam}Aligned.sortedByCoord.rg_added.bam O=${bam}Aligned.sortedByCoord.rg_added.dedupped.bam  CREATE_INDEX=true VALIDATION_STRINGENCY=SILENT M=${bam}Aligned.picard.metrics
java -jar /hpcf/apps/picard/install/2.9.4/picard.jar ReorderSam I=${bam}Aligned.sortedByCoord.rg_added.dedupped.bam O=${bam}Aligned.sortedByCoord.rg_added.dedupped.reordered.bam R=${ref} CREATE_INDEX=TRUE
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T SplitNCigarReads -R $ref -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.reordered.bam -o ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.bam -rf ReassignOneMappingQuality -RMQF 255 -RMQT 60 -U ALLOW_N_CIGAR_READS
echo -e "["$(date)"]\tCreating targets for indel realignment.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T RealignerTargetCreator -R $ref -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.bam -o ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.intervals -known $millsIndels -known $KGIndels
echo -e "["$(date)"]\tPerforming Indel Realignment.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T IndelRealigner -R $ref -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.bam -targetIntervals ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.intervals -known $millsIndels -known $KGIndels -o ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner.bam
echo -e "["$(date)"]\tPerforming BQSR.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T BaseRecalibrator -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner.bam  -R $ref -knownSites $KGIndels -knownSites $millsIndels -knownSites $dbSNP138 -o ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner_recal.table
echo -e "["$(date)"]\tPrinting recalibrated reads.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T PrintReads -R $ref -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner.bam -BQSR ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner_recal.table -o ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner.BQSR.bam
echo -e "["$(date)"]\tRunning HaplotypeCaller.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T HaplotypeCaller -R $ref -I ${bam}Aligned.sortedByCoord.rg_added.dedupped.split.IndelRealigner.BQSR.bam  -dontUseSoftClippedBases -stand_call_conf 20.0 -o ${bam}.vcf
echo -e "["$(date)"]\tFiltering Variants.."
java -jar /hpcf/apps/gatk/install/3.5/GenomeAnalysisTK.jar -T VariantFiltration -R $ref -V ${bam}.vcf -window 35 -cluster 3 -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o ${bam}_filtered.vcf
echo -e "["$(date)"]\tDONE!"
module load samtools/1.9
module load bcftools/1.15.1
vcfutils.pl varFilter -d 10 -p ${bam}_filtered.vcf > ${bam}_bcftools_filtered.vcf
bcftools +fill-tags ${bam}_bcftools_filtered.vcf  -- -t VAF > ${bam}.GTAK.bcftools.final.vcf

