

#BSUB -P cut_run
#BSUB -o cut_run_rfeng_2022-01-18.all.bw.message_%J_%I.out -e cut_run_rfeng_2022-01-18.all.bw.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4500]"
#BSUB -J "all.bw[1-21]"
module purge
#BSUB -w "ended(146946518[*])"
#BSUB -R "select[rhel7]"
module load conda3/202011
source activate /home/yli11/.conda/envs/captureC

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

bamCoverage -b ${COL3}.markdup.bam -o ${COL3}.all.bw --smoothLength=200 --ignoreForNormalization chrX chrM   --effectiveGenomeSize 2451960000 --numberOfProcessors 6 --centerReads

		